// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcdojmlpemgbrgvadoxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjZG9qbWxwZW1nYnJndmFkb3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTgzMTAsImV4cCI6MjA2NTkzNDMxMH0.kfXz1f2PKWR02PmN9RG8i0Z9_5xGX9LvVzE6hBpF3sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);